// ════════════════════════════════════════════
//  UTILS — Shared helper functions
// ════════════════════════════════════════════

// ── HTML escaping ────────────────────────────

function escHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}


function renderRichText(text) {
  if (!text) return '';
  let s = escHtml(text);
  s = s.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
  s = s.replace(/\n/g, '<br>');
  return sanitizeHtml(s);
}

// ── HTML sanitization ────────────────────────
// Allowlist-based sanitizer for HTML generated by renderRichText().
// Strips any tag not in the allowlist and removes dangerous attributes
// (event handlers, javascript: hrefs) from allowed tags.

function sanitizeHtml(html) {
  if (!html) return '';
  const ALLOWED_TAGS = new Set(['strong', 'em', 'br', 'a', 'span']);
  // Allowlist-based: only keep the tag itself (and, for <a>, a validated href).
  // This is safer than stripping individual dangerous attributes because it
  // cannot be bypassed by unusual attribute formatting.
  let s = html.replace(/<([a-z][a-z0-9]*)((?:\s[^>]*)?)\s*\/?>/gi, (match, tag, attrs) => {
    const lowerTag = tag.toLowerCase();
    if (!ALLOWED_TAGS.has(lowerTag)) return '';
    // For <a> tags extract only a safe href attribute; drop everything else
    if (lowerTag === 'a') {
      const hrefMatch = (attrs || '').match(/\s+href\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+))/i);
      if (hrefMatch) {
        const raw = hrefMatch[1] !== undefined ? hrefMatch[1]
                  : hrefMatch[2] !== undefined ? hrefMatch[2]
                  : hrefMatch[3] || '';
        // Normalize: strip whitespace/control chars that can bypass protocol checks
        const href = raw.replace(/[\s\u0000-\u001f]/g, '');
        if (/^(https?:|tel:|mailto:)/i.test(href)) {
          return `<a href="${href}">`;
        }
      }
      return '<a>';
    }
    // All other allowed tags: keep the tag name only, drop all attributes
    return `<${lowerTag}>`;
  });
  // Remove closing tags for disallowed elements
  s = s.replace(/<\/([a-z][a-z0-9]*)\s*>/gi, (match, tag) => {
    return ALLOWED_TAGS.has(tag.toLowerCase()) ? `</${tag.toLowerCase()}>` : '';
  });
  return s;
}

// ── PIN / credentials hashing ────────────────

async function hashPin(pin) {
  const buf = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(pin));
  return Array.from(new Uint8Array(buf)).map(b => b.toString(16).padStart(2, '0')).join('');
}

// ── UI feedback helpers ───────────────────────
// Single implementation replacing duplicate showErr/showOk definitions.

function showMsg(el, text, type) {
  if (!el) { alert((type === 'error' ? '❌ ' : '✅ ') + text); return; }
  el.style.color = type === 'error' ? 'var(--accent)' : 'var(--teal)';
  el.textContent = (type === 'error' ? '❌ ' : '✅ ') + text;
}

function showErr(el, text) { showMsg(el, text, 'error'); }
function showOk(el, text)  { showMsg(el, text, 'ok'); }
